apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-service-config
data:
  application.yaml: |
    server:
      port: {{ .Values.service.targetPort }}
    spring:
      profiles:
        active: {{ index .Values "service-config" "spring" "profile" }}
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${mysql-url}
        username: ${mysql-username}
        password: ${mysql-password}
      data:
        mongodb:
          uri: ${mongodb-url}
      jpa:
        hibernate:
          ddl-auto: none
        open-in-view: false
        show-sql: false
      security:
        oauth2:
          client:
            registration:
              google:
                clientId: ${google-client-id}
                clientSecret: ${google-client-secret}
                scope:
                  - email
                  - profile
              facebook:
                clientId: ${facebook-client-id}
                clientSecret: ${facebook-client-secret}
                scope:
                  - email
                  - public_profile
      servlet:
        multipart:
          max-file-size: {{ index .Values "service-config" "spring" "servlet" "multipart" "max-file-size" }}
          max-request-size: {{ index .Values "service-config" "spring" "servlet" "multipart" "max-request-size" }}
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          probes:
            enabled: true
    blas:
      aliasBlasPrivateKey: {{ index .Values "service-config" "blas" "aliasBlasPrivateKey" }}
      certificate: {{ index .Values "service-config" "blas" "certificate" }}
      image:
        imgbb:
          enabled: {{ index .Values "service-config" "blas" "image" "imgbb" "enabled" }}
          url: {{ index .Values "service-config" "blas" "image" "imgbb" "url" }}
          privateKey: ${imgbb-private-key}
          expirationTime: {{ index .Values "service-config" "blas" "image" "imgbb" "expirationTime" }}
      service:
        serviceName: {{ .Chart.Name }}
      gate-interceptor:
        enableLogRequest: {{ index .Values "service-config" "blas" "gate-interceptor" "enableLogRequest" }}
        enableLogLocalRequest: {{ index .Values "service-config" "blas" "gate-interceptor" "enableLogLocalRequest" }}
      blas-service-support:
        throughServiceSupport: {{ index .Values "service-config" "blas" "blas-service-support" "throughServiceSupport" }}
        endpointCheckMaintenance: {{ index .Values "service-config" "blas" "blas-service-support" "endpointCheckMaintenance" }}
      blas-idp:
        isSendEmailAlert: {{ index .Values "service-config" "blas" "blas-idp" "isSendEmailAlert" }}
        jwt:
          timeToExpired: {{ index .Values "service-config" "blas" "blas-idp" "jwt" "timeToExpired" }}
      hazelcast:
        aksNamespace: {{ .Values.aksNamespace }}
        hazelcastService: {{ .Values.hazelcastService }}

    logging:
      level:
{{- range $key, $value := index .Values "service-config" "logging" "level" }}
        {{ $key }}: {{ $value }}
{{- end }}

  hazelcast-client.yaml: |-
    hazelcast-client:
      network:
        kubernetes:
          enabled: {{ index .Values "service-config" "hazelcast-client" "network" "kubernetes" "enabled" }}

  bootstrap.yaml: |-
    spring:
      cloud:
        vault:
          authentication: KUBERNETES
          kubernetes:
            role: {{ index .Values "service-config" "vault" "kubernetes" "role" }}
            service-account-token-file: {{ index .Values "service-config" "vault" "kubernetes" "service-account-token-file" }}
          uri: {{ index .Values "service-config" "vault" "uri" }}
          namespace: {{ index .Values "service-config" "vault" "namespace" }}
          kv:
            backend: {{ index .Values "service-config" "vault" "kv" "backend" }}
            application-name: {{ index .Values "service-config" "vault" "kv" "application-name" }}
            default-context: {{ index .Values "service-config" "vault" "kv" "default-context" }}
          enabled: {{ index .Values "service-config" "vault" "enabled" }}
          connection-timeout: {{ index .Values "service-config" "vault" "connection-timeout" }}
          read-timeout: {{ index .Values "service-config" "vault" "read-timeout" }}
