apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: ClusterIP
  ports:
    - port: 5701
      protocol: TCP
  selector:
    hazelcast: {{.Values.hazelcastService}}
