apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blas-pvc
  labels:
    type: volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "hostpath"
