apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "blas-idp.fullname" . }}
  labels:
    {{- include "blas-idp.labels" . | nindent 4 }}
spec:
  strategy:
    blueGreen:
      activeService: {{ include "blas-idp.fullname" . }}
      previewService: {{ include "blas-idp.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.strategy.blueGreen.autoPromotionEnabled }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisions }}
  selector:
    matchLabels:
      {{- include "blas-idp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blas-idp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        hazelcast: {{ .Values.hazelcastService }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: blas-service-account
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OTEL_JAVAAGENT_EXTENSIONS
              value: "./blas-opentelemetry-agent-extension.jar"
            - name: OTEL_INSTRUMENTATION_BLAS_MASKED_TAGS
              value: "chat_id"
            - name: OTEL_INSTRUMENTATION_BLAS_MASKED_PATTERNS
              value: "Do%20not%20disclose%20the%20verification%20code%20to%20anyone%5C.%20Your%20authentication%20code%20will%20expire%20in%20\\d+%20\\S+%5C.%20Your%20verification%5C:%20([a-zA-Z0-9]+)&chat_id=,https://api.telegram.org/bot([a-zA-Z0-9_-]+):([a-zA-Z0-9_-]+)"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            - name: multicast
              containerPort: 5701
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Chart.Name }}-config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            name: {{ .Chart.Name }}-service-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
