server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
blas:
  blas-idp:
    isSendEmailAlert: true
    jwt:
      secret: ZPYu33tz8QYU3hwJQXgHpZsKfYn0r2poopBx7x1n3rmeIvuGU4wf65kk6rV1DrN
      timeToExpired: 8640000 #100 days
  blas-email:
    endpointHtmlEmail: http://localhost:8082/send-email/html
    endpointHtmlEmailWithAttachments: http://localhost:8082/send-email/html-with-attachment

#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG
