server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blas
    username: root
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
blas:
  aliasBlasPrivateKey: blasSecretKey
  certificate: BlasSecretKey.p12
  service:
    serviceName: blas-idp
  gate-interceptor:
    enableLogRequest: true
    enableLogLocalRequest: false
  blas-support-service:
    maintenance:
      endpointCheck: http://localhost:8084/maintenance/check
  blas-idp:
    isSendEmailAlert: true
    jwt:
      timeToExpired: 8640000 #100 days
      timeToExpiredInternalToken: 120 #2 minutes
  blas-email:
    endpointHtmlEmail: http://localhost:8082/send-email/html
    endpointHtmlEmailWithAttachments: http://localhost:8082/send-email/html-with-attachment

#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG
