server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blas
#    username: root
#    password:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6499055
    username: sql6499055
    password: 6gPWwT2nr9
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG