server:
  port: 8067
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql-url-local}
    username: ${mysql-username}
    password: ${mysql-password}
  data:
    mongodb:
      uri: ${mongodb-url}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google-client-id}
            clientSecret: ${google-client-secret}
            scope:
              - email
              - profile
          facebook:
            clientId: ${facebook-client-id}
            clientSecret: ${facebook-client-secret}
            scope:
              - email
              - public_profile
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
blas:
  aliasBlasPrivateKey: blasSecretKey
  certificate: BlasSecretKey.p12
  service:
    serviceName: blas-idp
  gate-interceptor:
    enableLogRequest: true
    enableLogLocalRequest: false
  blas-service-support:
    throughServiceSupport: true
    endpointCheckMaintenance: http://localhost:8084/maintenance/check
  blas-idp:
    isSendEmailAlert: true
    jwt:
      timeToExpired: 8640000 #100 days
  hazelcast:
    aksNamespace: dev
    hazelcastService: hazelcast

logging:
  level:
    root: INFO
    com.blas: INFO
    org.hibernate: WARN
    com.azure: WARN
    io.micrometer: WARN
    com.hazelcast: ERROR
    org.mongodb: WARN
    org.springframework: WARN
    org.apache.http: WARN
