server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: fjuyjuvh
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/fjuyjuvh
    password: Jb0wvvaz3NUxFFpEf2QIT_n1Uirwl7lK
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

#logging:
#  file:
#    name: application.log
#  level:
#    root: DEBUG
#    org.springframework: WARN
#    com.example.TaskManagement.service: DEBUG